# Generated by Django 5.1.6 on 2025-05-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="size",
            field=models.IntegerField(default=0),
        ),
    ]
