# Generated by Django 5.1.6 on 2025-05-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_products_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="color",
            field=models.CharField(default="", max_length=20),
        ),
    ]
