# Generated by Django 5.1.6 on 2025-05-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_products_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="stock",
            field=models.CharField(default="", max_length=10),
        ),
    ]
