# Generated by Django 5.1.6 on 2025-05-12 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_products_stock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=12)),
                ("adderessline1", models.CharField(max_length=100)),
                ("adderessline2", models.CharField(max_length=100)),
                ("adderessline3", models.CharField(max_length=100)),
                ("pin", models.IntegerField()),
                ("city", models.CharField(max_length=25)),
                ("state", models.CharField(max_length=40)),
                (
                    "pic",
                    models.ImageField(default="", null=True, upload_to="shop/images"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
