# Generated by Django 5.1.6 on 2025-05-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_buyer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=50)),
                ("price", models.IntegerField(default=0)),
                ("image", models.ImageField(default="", upload_to="shop/images")),
            ],
        ),
        migrations.AlterField(
            model_name="buyer",
            name="pic",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="shop/images"
            ),
        ),
    ]
