# Generated by Django 5.1.6 on 2025-06-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="size",
            field=models.CharField(max_length=5),
        ),
    ]
